import { NextResponse } from "next/server";
import { chemicalsRepository } from "@/lib/chemicals/repository";
import { organizationRepository } from "@/lib/organization/repository";
import { demoStore } from "@/lib/demo-store";
import { isDemoMode } from "@/lib/demo-mode";

export async function GET() {
  const chemicals = await chemicalsRepository.getChemicals();
  const org =
    (await organizationRepository.getOrganization()) ??
    (isDemoMode() ? demoStore.getOrganization() : null);
  if (!org) {
    return new NextResponse("Organization not found", { status: 404 });
  }

  const rows = chemicals.map((c) => ({
    name: c.name,
    type: c.chemical_type,
    cas: c.cas_number ?? "N/A",
    location: c.storage_location ?? "N/A",
    sdsStatus: c.sds_status,
    sdsVersion: c.sds_version ?? "N/A",
    ppe: (c.ppe_required ?? []).join(", ") || "N/A",
  }));

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>HazCom Report - ${org.name}</title>
  <style>
    body { font-family: Inter, system-ui, sans-serif; margin: 40px; color: #111827; }
    h1 { color: #1D4ED8; font-size: 24px; }
    .subtitle { color: #6B7280; font-size: 14px; margin-bottom: 24px; }
    table { width: 100%; border-collapse: collapse; font-size: 13px; }
    th { background: #F3F4F6; text-align: left; padding: 10px; border-bottom: 2px solid #E5E7EB; }
    td { padding: 10px; border-bottom: 1px solid #E5E7EB; }
    .compliant { background: #F0FDF4; }
    .missing, .outdated { background: #FEF2F2; }
    .review_due { background: #FFFBEB; }
    footer { margin-top: 32px; font-size: 12px; color: #9CA3AF; }
  </style>
</head>
<body>
  <h1>SafeCellar Hazard Communication Plan</h1>
  <p class="subtitle"><strong>${org.name}</strong> · ${org.address ?? ""} ${org.city ?? ""}, ${org.state ?? ""} · Prepared for OSHA Inspection · Generated ${new Date().toLocaleDateString()}</p>
  <table>
    <thead>
      <tr>
        <th>Chemical Name</th><th>Type</th><th>CAS</th><th>Location</th><th>SDS Status</th><th>SDS Version</th><th>PPE Required</th>
      </tr>
    </thead>
    <tbody>
      ${rows
        .map(
          (r) => `<tr class="${r.sdsStatus}">
        <td>${r.name}</td><td>${r.type}</td><td>${r.cas}</td><td>${r.location}</td>
        <td>${r.sdsStatus}</td><td>${r.sdsVersion}</td><td>${r.ppe}</td>
      </tr>`
        )
        .join("")}
    </tbody>
  </table>
  <footer>Generated by SafeCellar on ${new Date().toLocaleDateString()}. All SDS documents on file.</footer>
</body>
</html>`;

  return new NextResponse(html, {
    headers: {
      "Content-Type": "text/html",
      "Content-Disposition": `attachment; filename="hazcom-report-${org.name.replace(/\s+/g, "-").toLowerCase()}.html"`,
    },
  });
}
